//
//  PDFExporter.swift
//  BrightJournal
//
//  Created by AI Assistant on 03/09/2025.
//

import PDFKit
import SwiftUI
import UIKit

enum PDFExporter {
    static func makeMonthlySummaryPDF(title: String, body: String) -> URL? {
        let tmp = URL(fileURLWithPath: NSTemporaryDirectory())
            .appendingPathComponent("BrightJournal-\(UUID().uuidString).pdf")

        let pdfMeta: [String: Any] = [
            kCGPDFContextTitle as String: title,
            kCGPDFContextCreator as String: "BrightJournal"
        ]
        let pageRect = CGRect(x: 0, y: 0, width: 612, height: 792) // US Letter @72dpi
        
        guard UIGraphicsBeginPDFContextToFile(tmp.path, pageRect, pdfMeta) else {
            return nil
        }
        
        UIGraphicsBeginPDFPage()

        // Draw title
        let titleAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 22, weight: .semibold),
            .foregroundColor: UIColor.label
        ]
        let bodyAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 13),
            .foregroundColor: UIColor.label
        ]
        let footerAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 10),
            .foregroundColor: UIColor.secondaryLabel
        ]
        
        let inset: CGFloat = 40
        let titleRect = CGRect(x: inset, y: inset, width: pageRect.width - inset*2, height: 40)
        (title as NSString).draw(in: titleRect, withAttributes: titleAttrs)

        // Draw body
        let bodyRect = CGRect(x: inset, y: titleRect.maxY + 16, width: pageRect.width - inset*2, height: pageRect.height - titleRect.maxY - 100)
        (body as NSString).draw(in: bodyRect, withAttributes: bodyAttrs)
        
        // Draw footer
        let footerText = "Generated by Bright Journal - AI-powered personal reflection"
        let footerRect = CGRect(x: inset, y: pageRect.height - 60, width: pageRect.width - inset*2, height: 20)
        (footerText as NSString).draw(in: footerRect, withAttributes: footerAttrs)

        UIGraphicsEndPDFContext()
        return FileManager.default.fileExists(atPath: tmp.path) ? tmp : nil
    }
}